### ISSUE TITLE
Add styling to the Home page

### ISSUE THREAD

**Issue by CalvinSithideth** [CalvinSithideth/CPW213-eCommerceSite#12]
Home/Index should have some CSS or Bootstrap styling.
https://getbootstrap.com/docs/4.3/components/alerts/

**Comment by Shivansh2407** [comment]
https://css-tricks.com/lodge/v10/138-forums-homepage-styling/

https://css-tricks.com/snippets/css/

You can see these too!

**Comment by Shivansh2407** [comment]
If you need help Please let me know : )

**Comment by CalvinSithideth** [comment]
Thanks for the input, @Shivansh2407 !
